# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class TorrancecaItem(scrapy.Item):
###### Agregar los atributos a la class
    kukun_permit_id = scrapy.Field()
    permit_number = scrapy.Field()
    status_date = scrapy.Field()
    status = scrapy.Field()

    building_type_unformatted = scrapy.Field()
    permit_type_unformatted = scrapy.Field()
    permit_sub_type_unformatted = scrapy.Field()
    permit_description = scrapy.Field()
    city_assigned_cost = scrapy.Field()
    house_owner_name = scrapy.Field()
    house_owner_phone = scrapy.Field()
    house_owner_street_address = scrapy.Field()
    house_owner_city = scrapy.Field()
    house_owner_state = scrapy.Field()
    house_owner_zip = scrapy.Field()
    tenant_name = scrapy.Field()
    house_street_address = scrapy.Field()
    house_city = scrapy.Field()
    house_state = scrapy.Field()
    house_zip = scrapy.Field()
    house_latitude = scrapy.Field()
    house_longitude = scrapy.Field()
    contractor_company = scrapy.Field()
    contractor_name = scrapy.Field()
    contractor_phone = scrapy.Field()
    contractor_license = scrapy.Field()
    email_contractor = scrapy.Field()
    contractor_street_address = scrapy.Field()
    contractor_city = scrapy.Field()
    contractor_state = scrapy.Field()
    contractor_zip = scrapy.Field()
    cost_contractor = scrapy.Field()
    fee_contractor = scrapy.Field()
    bussines_type_contractor = scrapy.Field()
    
    applicant_name = scrapy.Field()
    applicant_phone = scrapy.Field()
    applicant_email = scrapy.Field()
    applicant_street_address = scrapy.Field()
    applicant_city = scrapy.Field()
    applicant_state = scrapy.Field()
    applicant_zip = scrapy.Field()
    permit_source_city = scrapy.Field()
    permit_source_state = scrapy.Field()
    permit_source_county = scrapy.Field()
    master_permit_number = scrapy.Field()
    house_parcel_number = scrapy.Field()
    LOT = scrapy.Field()
    number_of_stories = scrapy.Field()
    number_of_rooms = scrapy.Field()
    square_footage = scrapy.Field()
    total_new_add_footage = scrapy.Field()
    permit_expiry_date = scrapy.Field()
    permit_fee = scrapy.Field()
    amount_waived = scrapy.Field()
    city_block = scrapy.Field()
    borough = scrapy.Field()
    zoning = scrapy.Field()
    lender = scrapy.Field()
    inspection_violation_description = scrapy.Field()
    inspection_status = scrapy.Field()
    inspection_date = scrapy.Field()
    violation_fee = scrapy.Field()
    inspector_first_and_last_name = scrapy.Field()